### PR TITLE
wrap notfound template with Layout component

### LINKED ISSUE #143: Page Not Found is not using Layout
**Describe the bug**
When visiting a route that doesn't exist, an unstyled 404 page appears. 

**To Reproduce**

1. Visit any page not in the routes file.

**Expected behavior**
The Page not found has the Layout component wrapping it so it looks like a page not a server response.

### PR DESCRIPTION
**Pull request by dgading**
fixes #143

The NotFound template just had an H1 with no Layout component wrapping it. This meant the header and footer wouldn't load on the page.

### CODE REVIEW

File: src/templates/not_found/index.jsx [hunk 1]
```diff
@@ -1,8 +1,14 @@
 import React from 'react';
+import Layout from '../../components/Layout';
 
 const NotFound = () => {
   return (
-    <h1>Page not found.</h1>
+    <Layout title="Dataset Publishers">
```
Comment (brdunfield) [inline src/templates/not_found/index.jsx:6]: Nitpick but this layout title should probably be changed

Comment (dgading) [reply src/templates/not_found/index.jsx]: I just pushed an update to change to `Page not found`

**Review by brdunfield — APPROVED** [review]
✅
